@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJ0ZXN0QGV4YW1wbGUuY29tIiwiaWF0IjoxNzQzMzI4MDE2LCJleHAiOjE3NDM0MTQ0MTZ9.tM-5_TUec716msY9tAH63zWLkYok9JyUWsiVQGcS8SM

### [400 BAD REQUEST] Movie Save
POST http://localhost:3000/api/movie
Content-Type: application/json
Authorization: Bearer {{token}}

### [201 SUCCESS] Movie Save
POST http://localhost:3000/api/movie
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "movie_id": 1,
  "title": "batman",
  "poster_url": "poster url test"
}

### [200 SUCCESS] Get Movies
GET http://localhost:3000/api/movie
Content-Type: application/json
Authorization: Bearer {{token}}

### [404 NOT FOUND] Delete Movies
DELETE http://localhost:3000/api/movie/3913
Content-Type: application/json
Authorization: Bearer {{token}}

### [404 NOT FOUND] Delete Movies
DELETE http://localhost:3000/api/movie/1
Content-Type: application/json
Authorization: Bearer {{token}}
