@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJ0ZXN0QGV4YW1wbGUuY29tIiwiaWF0IjoxNzQzMzQ2MDg4LCJleHAiOjE3NDM0MzI0ODh9.x0-8A-irPoN2SiamOIg97rPvCXCkHQi87-xSmw4oPGE

### [200 SUCCESS] Get User
GET http://localhost:3000/api/user
Content-Type: application/json
Authorization: Bearer {{token}}
